# Generated by Django 5.1.3 on 2025-03-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scname', models.CharField(max_length=100)),
                ('scloc', models.CharField(max_length=100)),
                ('scprincipal', models.CharField(max_length=100)),
            ],
        ),
    ]
